### PR TITLE
Add support for returning results using Postgres' binary format

### LINKED ISSUE #26: Support binary results
We're storing large binary data in our DB. We saw a 3x speedup when inserting the data using binary format, vs using escaped text.

However, I don't see a way to get binary data out of postgres without escaping it. I believe that is due to [this line](https://github.com/mmottl/postgresql-ocaml/blob/10f513c0073f19ce961105ea2619ee6f158ad1ac/src/postgresql_stubs.c#L643), in which the resultFormat is 0 (indicating text) with no way of setting it to 1.

Does this seem right? Can we add a way of setting it to 1 to get output as binary?

### PR DESCRIPTION
**Pull request by pbiggar**
Tested in examples/binary.ml. Fixes #26.

### CODE REVIEW

**Comment by mmottl** [comment]
Thanks a lot for the patch!

**Comment by pbiggar** [comment]
No problem. Would it be possible for you to release the new 4.4.0 on opam? Thanks!

**Comment by mmottl** [comment]
Yes, I always submit new releases to OPAM automatically.  The current pull request was temporarily denied due to a recently added restriction in OPAM.  I've just fixed this and expect the OPAM submission to go through soon.

**Comment by pbiggar** [comment]
I see it published. Thanks again!

**Pull request merged**
